#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const outDir = path.join("dist", "sitemap");
fs.mkdirSync(outDir, { recursive: true });

const html = [
  "<!doctype html>",
  "<html>",
  "<head>",
  '  <meta charset="utf-8"/>',
  "  <title>STLDNB Drillable Sitemap</title>",
  '  <meta name="viewport" content="width=device-width, initial-scale=1"/>',
  "  <style>",
  "    body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial;}",
  "    header{padding:10px;border-bottom:1px solid #e5e7eb;background:#fff;position:sticky;top:0;z-index:10;}",
  "    .row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;}",
  "    button,a.btn{padding:8px 10px;border:1px solid #d1d5db;background:#fff;border-radius:8px;cursor:pointer;text-decoration:none;color:#111;}",
  "    #viewport{width:100vw;height:calc(100vh - 58px);overflow:hidden;background:#fafafa;}",
  "    #stage{transform-origin:0 0;}",
  "    .hint{color:#6b7280;font-size:13px;}",
  "  </style>",
  "</head>",
  "<body>",
  "  <header>",
  '    <div class="row">',
  '      <button id="btnOverview">Overview</button>',
  '      <button id="btnFull">Full</button>',
  '      <a class="btn" href="sitemap.svg" target="_blank">SVG overview</a>',
  '      <a class="btn" href="unified.svg" target="_blank">SVG full</a>',
  '      <span class="hint">Drag to pan • Ctrl/Cmd+wheel to zoom • Double-click to reset</span>',
  "    </div>",
  "  </header>",
  '  <div id="viewport"><div id="stage"></div></div>',
  "",
  '  <script type="module">',
  '    import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";',
  "    mermaid.initialize({ startOnLoad:false, securityLevel:'loose', flowchart:{ useMaxWidth:false } });",
  "",
  "    const viewport = document.getElementById('viewport');",
  "    const stage = document.getElementById('stage');",
  "    let scale = 1, tx = 20, ty = 20;",
  "    let isPanning = false, startX = 0, startY = 0;",
  "",
  "    function apply(){ stage.style.transform = 'translate(' + tx + 'px,' + ty + 'px) scale(' + scale + ')'; }",
  "    function reset(){ scale = 1; tx = 20; ty = 20; apply(); }",
  "    function clamp(s){ return Math.min(3, Math.max(0.2, s)); }",
  "",
  "    viewport.addEventListener('mousedown', (e)=>{",
  "      isPanning = true;",
  "      startX = e.clientX - tx;",
  "      startY = e.clientY - ty;",
  "      viewport.style.cursor = 'grabbing';",
  "    });",
  "    window.addEventListener('mouseup', ()=>{ isPanning=false; viewport.style.cursor='default'; });",
  "    window.addEventListener('mousemove', (e)=>{",
  "      if(!isPanning) return;",
  "      tx = e.clientX - startX;",
  "      ty = e.clientY - startY;",
  "      apply();",
  "    });",
  "",
  "    viewport.addEventListener('wheel', (e)=>{",
  "      if(!(e.ctrlKey || e.metaKey)) return;",
  "      e.preventDefault();",
  "      const prev = scale;",
  "      const next = clamp(scale * (e.deltaY < 0 ? 1.1 : 0.9));",
  "      const rect = viewport.getBoundingClientRect();",
  "      const cx = e.clientX - rect.left;",
  "      const cy = e.clientY - rect.top;",
  "      tx = cx - (cx - tx) * (next / prev);",
  "      ty = cy - (cy - ty) * (next / prev);",
  "      scale = next;",
  "      apply();",
  "    }, { passive:false });",
  "",
  "    viewport.addEventListener('dblclick', reset);",
  "",
  "    async function renderMmd(file){",
  "      const src = await fetch(file).then(r=>r.text());",
  "      const id = 'mmd_' + Math.random().toString(16).slice(2);",
  "      const out = await mermaid.render(id, src);",
  "      stage.innerHTML = out.svg;",
  "      stage.querySelectorAll('a').forEach(a=>a.setAttribute('target','_blank'));",
  "      reset();",
  "    }",
  "",
  "    document.getElementById('btnOverview').addEventListener('click', ()=>renderMmd('index.mmd'));",
  "    document.getElementById('btnFull').addEventListener('click', ()=>renderMmd('unified.mmd'));",
  "    renderMmd('index.mmd');",
  "  </script>",
  "</body>",
  "</html>",
].join("\n");

fs.writeFileSync(path.join(outDir, "index.html"), html, "utf8");
console.log("✅ Wrote dist/sitemap/index.html");
